/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/account/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["LoginDto"];
                    "application/json": components["schemas"]["LoginDto"];
                    "text/json": components["schemas"]["LoginDto"];
                    "application/*+json": components["schemas"]["LoginDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchanges the refresh cookie for a new access token and a rotated refresh cookie.
         *     Anonymous by design: the caller reaches here precisely because its access token has expired.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revokes the whole token family behind the current refresh cookie and clears it.
         *     Anonymous so that signing out still works once the access token has expired.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The authenticated caller's own profile and roles, without minting a new token. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["CurrentUserDto"];
                        "application/json": components["schemas"]["CurrentUserDto"];
                        "text/json": components["schemas"]["CurrentUserDto"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/account/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Changes the password, then signs every other device out and re-establishes the current
         *     session, so the caller stays logged in here but stolen sessions elsewhere die.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["ChangePasswordDto"];
                    "application/json": components["schemas"]["ChangePasswordDto"];
                    "text/json": components["schemas"]["ChangePasswordDto"];
                    "application/*+json": components["schemas"]["ChangePasswordDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AuthResponseDto"];
                        "application/json": components["schemas"]["AuthResponseDto"];
                        "text/json": components["schemas"]["AuthResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Unauthorized */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    from?: string;
                    to?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["AnalyticsDashboardDto"];
                        "application/json": components["schemas"]["AnalyticsDashboardDto"];
                        "text/json": components["schemas"]["AnalyticsDashboardDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/employees-by-department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeDepartmentStatsDto"][];
                        "application/json": components["schemas"]["EmployeeDepartmentStatsDto"][];
                        "text/json": components["schemas"]["EmployeeDepartmentStatsDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponseDto"][];
                        "application/json": components["schemas"]["DepartmentResponseDto"][];
                        "text/json": components["schemas"]["DepartmentResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateDepartmentRequestDto"];
                    "application/json": components["schemas"]["CreateDepartmentRequestDto"];
                    "text/json": components["schemas"]["CreateDepartmentRequestDto"];
                    "application/*+json": components["schemas"]["CreateDepartmentRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponseDto"];
                        "application/json": components["schemas"]["DepartmentResponseDto"];
                        "text/json": components["schemas"]["DepartmentResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/department/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponseDto"];
                        "application/json": components["schemas"]["DepartmentResponseDto"];
                        "text/json": components["schemas"]["DepartmentResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateDepartmentRequestDto"];
                    "application/json": components["schemas"]["CreateDepartmentRequestDto"];
                    "text/json": components["schemas"]["CreateDepartmentRequestDto"];
                    "application/*+json": components["schemas"]["CreateDepartmentRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentResponseDto"];
                        "application/json": components["schemas"]["DepartmentResponseDto"];
                        "text/json": components["schemas"]["DepartmentResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeResponseDto"][];
                        "application/json": components["schemas"]["EmployeeResponseDto"][];
                        "text/json": components["schemas"]["EmployeeResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateEmployeeRequestDto"];
                    "application/json": components["schemas"]["CreateEmployeeRequestDto"];
                    "text/json": components["schemas"]["CreateEmployeeRequestDto"];
                    "application/*+json": components["schemas"]["CreateEmployeeRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeResponseDto"];
                        "application/json": components["schemas"]["EmployeeResponseDto"];
                        "text/json": components["schemas"]["EmployeeResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeResponseDto"];
                        "application/json": components["schemas"]["EmployeeResponseDto"];
                        "text/json": components["schemas"]["EmployeeResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateEmployeeRequestDto"];
                    "application/json": components["schemas"]["UpdateEmployeeRequestDto"];
                    "text/json": components["schemas"]["UpdateEmployeeRequestDto"];
                    "application/*+json": components["schemas"]["UpdateEmployeeRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["EmployeeResponseDto"];
                        "application/json": components["schemas"]["EmployeeResponseDto"];
                        "text/json": components["schemas"]["EmployeeResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/employee/{id}/toggle-active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/employee/{id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sets a new password for an employee who cannot sign in. There is no self-service reset,
         *     so this is the only recovery path for a forgotten password.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["ResetPasswordDto"];
                    "application/json": components["schemas"]["ResetPasswordDto"];
                    "text/json": components["schemas"]["ResetPasswordDto"];
                    "application/*+json": components["schemas"]["ResetPasswordDto"];
                };
            };
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceResponseDto"][];
                        "application/json": components["schemas"]["ResourceResponseDto"][];
                        "text/json": components["schemas"]["ResourceResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateResourceRequestDto"];
                    "application/json": components["schemas"]["CreateResourceRequestDto"];
                    "text/json": components["schemas"]["CreateResourceRequestDto"];
                    "application/*+json": components["schemas"]["CreateResourceRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceResponseDto"];
                        "application/json": components["schemas"]["ResourceResponseDto"];
                        "text/json": components["schemas"]["ResourceResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceResponseDto"];
                        "application/json": components["schemas"]["ResourceResponseDto"];
                        "text/json": components["schemas"]["ResourceResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["PatchResourceRequestDto"];
                    "application/json": components["schemas"]["PatchResourceRequestDto"];
                    "text/json": components["schemas"]["PatchResourceRequestDto"];
                    "application/*+json": components["schemas"]["PatchResourceRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceResponseDto"];
                        "application/json": components["schemas"]["ResourceResponseDto"];
                        "text/json": components["schemas"]["ResourceResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/resource/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    } & {
                        name?: string;
                    } & {
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceResponseDto"];
                        "application/json": components["schemas"]["ResourceResponseDto"];
                        "text/json": components["schemas"]["ResourceResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource-engagement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["RecordResourceEngagementRequestDto"];
                    "application/json": components["schemas"]["RecordResourceEngagementRequestDto"];
                    "text/json": components["schemas"]["RecordResourceEngagementRequestDto"];
                    "application/*+json": components["schemas"]["RecordResourceEngagementRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceEngagementResponseDto"];
                        "application/json": components["schemas"]["ResourceEngagementResponseDto"];
                        "text/json": components["schemas"]["ResourceEngagementResponseDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource-engagement/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceEngagementResponseDto"][];
                        "application/json": components["schemas"]["ResourceEngagementResponseDto"][];
                        "text/json": components["schemas"]["ResourceEngagementResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource-engagement/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ResourceEngagementStatsDto"][];
                        "application/json": components["schemas"]["ResourceEngagementStatsDto"][];
                        "text/json": components["schemas"]["ResourceEngagementStatsDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resource-engagement/by-department": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DepartmentEngagementStatsDto"][];
                        "application/json": components["schemas"]["DepartmentEngagementStatsDto"][];
                        "text/json": components["schemas"]["DepartmentEngagementStatsDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-action": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultDtoOfRiskActionResponseDto"];
                        "application/json": components["schemas"]["PagedResultDtoOfRiskActionResponseDto"];
                        "text/json": components["schemas"]["PagedResultDtoOfRiskActionResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateRiskActionRequestDto"];
                    "application/json": components["schemas"]["CreateRiskActionRequestDto"];
                    "text/json": components["schemas"]["CreateRiskActionRequestDto"];
                    "application/*+json": components["schemas"]["CreateRiskActionRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskActionResponseDto"];
                        "application/json": components["schemas"]["RiskActionResponseDto"];
                        "text/json": components["schemas"]["RiskActionResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-action/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskActionSummaryDto"];
                        "application/json": components["schemas"]["RiskActionSummaryDto"];
                        "text/json": components["schemas"]["RiskActionSummaryDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-action/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskActionResponseDto"];
                        "application/json": components["schemas"]["RiskActionResponseDto"];
                        "text/json": components["schemas"]["RiskActionResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateRiskActionRequestDto"];
                    "application/json": components["schemas"]["UpdateRiskActionRequestDto"];
                    "text/json": components["schemas"]["UpdateRiskActionRequestDto"];
                    "application/*+json": components["schemas"]["UpdateRiskActionRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskActionResponseDto"];
                        "application/json": components["schemas"]["RiskActionResponseDto"];
                        "text/json": components["schemas"]["RiskActionResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-action/by-report/{reportId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    reportId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskActionResponseDto"][];
                        "application/json": components["schemas"]["RiskActionResponseDto"][];
                        "text/json": components["schemas"]["RiskActionResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    status?: string;
                    page?: number | string;
                    pageSize?: number | string;
                    search?: string;
                    sortBy?: string;
                    sortDir?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultDtoOfRiskReportResponseDto"];
                        "application/json": components["schemas"]["PagedResultDtoOfRiskReportResponseDto"];
                        "text/json": components["schemas"]["PagedResultDtoOfRiskReportResponseDto"];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateRiskReportRequestDto"];
                    "application/json": components["schemas"]["CreateRiskReportRequestDto"];
                    "text/json": components["schemas"]["CreateRiskReportRequestDto"];
                    "application/*+json": components["schemas"]["CreateRiskReportRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskReportResponseDto"];
                        "application/json": components["schemas"]["RiskReportResponseDto"];
                        "text/json": components["schemas"]["RiskReportResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-report/mine": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskReportResponseDto"][];
                        "application/json": components["schemas"]["RiskReportResponseDto"][];
                        "text/json": components["schemas"]["RiskReportResponseDto"][];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-report/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskReportResponseDto"];
                        "application/json": components["schemas"]["RiskReportResponseDto"];
                        "text/json": components["schemas"]["RiskReportResponseDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-report/{id}/auditor-evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Revises an auditor evaluation that already exists. Separate from the POST that creates
         *     one, so that creating twice stays an error rather than silently overwriting an
         *     assessment another auditor made.
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateEvaluationRequestDto"];
                    "application/json": components["schemas"]["CreateEvaluationRequestDto"];
                    "text/json": components["schemas"]["CreateEvaluationRequestDto"];
                    "application/*+json": components["schemas"]["CreateEvaluationRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskReportResponseDto"];
                        "application/json": components["schemas"]["RiskReportResponseDto"];
                        "text/json": components["schemas"]["RiskReportResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateEvaluationRequestDto"];
                    "application/json": components["schemas"]["CreateEvaluationRequestDto"];
                    "text/json": components["schemas"]["CreateEvaluationRequestDto"];
                    "application/*+json": components["schemas"]["CreateEvaluationRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskReportResponseDto"];
                        "application/json": components["schemas"]["RiskReportResponseDto"];
                        "text/json": components["schemas"]["RiskReportResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-report/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateRiskReportStatusRequestDto"];
                    "application/json": components["schemas"]["UpdateRiskReportStatusRequestDto"];
                    "text/json": components["schemas"]["UpdateRiskReportStatusRequestDto"];
                    "application/*+json": components["schemas"]["UpdateRiskReportStatusRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskReportResponseDto"];
                        "application/json": components["schemas"]["RiskReportResponseDto"];
                        "text/json": components["schemas"]["RiskReportResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/risk-report/{id}/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    page?: number | string;
                    pageSize?: number | string;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultDtoOfRiskReportStatusHistoryResponseDto"];
                        "application/json": components["schemas"]["PagedResultDtoOfRiskReportStatusHistoryResponseDto"];
                        "text/json": components["schemas"]["PagedResultDtoOfRiskReportStatusHistoryResponseDto"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-subcategory/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskCategoryResponseDto"][];
                        "application/json": components["schemas"]["RiskCategoryResponseDto"][];
                        "text/json": components["schemas"]["RiskCategoryResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-subcategory/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskSubcategoryResponseDto"];
                        "application/json": components["schemas"]["RiskSubcategoryResponseDto"];
                        "text/json": components["schemas"]["RiskSubcategoryResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["UpdateRiskSubcategoryRequestDto"];
                    "application/json": components["schemas"]["UpdateRiskSubcategoryRequestDto"];
                    "text/json": components["schemas"]["UpdateRiskSubcategoryRequestDto"];
                    "application/*+json": components["schemas"]["UpdateRiskSubcategoryRequestDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskSubcategoryResponseDto"];
                        "application/json": components["schemas"]["RiskSubcategoryResponseDto"];
                        "text/json": components["schemas"]["RiskSubcategoryResponseDto"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description No Content */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-subcategory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json-patch+json": components["schemas"]["CreateRiskSubcategoryRequestDto"];
                    "application/json": components["schemas"]["CreateRiskSubcategoryRequestDto"];
                    "text/json": components["schemas"]["CreateRiskSubcategoryRequestDto"];
                    "application/*+json": components["schemas"]["CreateRiskSubcategoryRequestDto"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskSubcategoryResponseDto"];
                        "application/json": components["schemas"]["RiskSubcategoryResponseDto"];
                        "text/json": components["schemas"]["RiskSubcategoryResponseDto"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/risk-subcategory/by-category/{category}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    category: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["RiskSubcategoryResponseDto"][];
                        "application/json": components["schemas"]["RiskSubcategoryResponseDto"][];
                        "text/json": components["schemas"]["RiskSubcategoryResponseDto"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ProblemDetails"];
                        "application/json": components["schemas"]["ProblemDetails"];
                        "text/json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyticsDashboardDto: {
            /** Format: double */
            riskAwarenessPercentage: number | string;
            earlyWarningIndicators: components["schemas"]["EarlyWarningIndicatorsDto"];
            outstandingActions: components["schemas"]["RiskActionSummaryDto"];
            /** Format: double */
            averageRiskResolutionTimeHours: null | number | string;
            /** Format: int32 */
            risksSubmittedThisWeek: number | string;
            /** Format: int32 */
            risksSubmittedThisMonth: number | string;
            risksByDepartment: components["schemas"]["CountByLabelDto"][];
            risksByLocation: components["schemas"]["CountByLabelDto"][];
            riskSubcategoryDistribution: components["schemas"]["CountByLabelDto"][];
            riskMaturityByDepartment: components["schemas"]["DepartmentMaturityDto"][];
            inherentRiskMatrix: components["schemas"]["InherentRiskMatrixDto"];
            residualRiskBands: components["schemas"]["ResidualRiskBandDto"][];
        };
        /**
         * @description Everything the client needs to run an authenticated session, returned by login, refresh
         *     and change-password alike so the SPA has one code path for establishing a session.
         *     The refresh token is deliberately absent: it travels only in an HttpOnly cookie.
         */
        AuthResponseDto: {
            accessToken: string;
            /** Format: date-time */
            accessTokenExpiresAt: string;
            roles: string[];
            /**
             * @description The caller's own employee profile. Its `id` is the value the API expects in the
             *     `empId` / `uploadedByEmpId` fields of request bodies, so the client never has
             *     to enumerate employees to discover who it is.
             */
            employee: components["schemas"]["EmployeeResponseDto"];
        };
        ChangePasswordDto: {
            currentPassword: string;
            newPassword: string;
        };
        CountByLabelDto: {
            label: string;
            /** Format: int32 */
            count: number | string;
        };
        CreateDepartmentRequestDto: {
            name: string;
            branchLocation: string;
        };
        CreateEmployeeRequestDto: {
            email: string;
            password: string;
            name: string;
            /** Format: int64 */
            deptId: number | string;
            role: string;
        };
        CreateEvaluationRequestDto: {
            /** Format: int32 */
            severity: number | string;
            /** Format: int32 */
            frequency: number | string;
            /** Format: int32 */
            controlEffectiveness: number | string;
            existingMeasures: null | string;
            proposedMeasures: null | string;
            /** Format: int32 */
            priority: number | string;
        };
        CreateResourceRequestDto: {
            name: string;
            /** Format: int64 */
            uploadedByEmpId: number | string;
            url: string;
            type: string;
            description?: null | string;
        };
        CreateRiskActionRequestDto: {
            /** Format: int64 */
            reportId: number | string;
            title: string;
            description: null | string;
            /** Format: int64 */
            assigneeEmpId: number | string;
            /** Format: date-time */
            dueDate: string;
        };
        CreateRiskReportRequestDto: {
            /** Format: int64 */
            empId: number | string;
            /** Format: int64 */
            subCategoryId: number | string;
            evaluation: components["schemas"]["CreateEvaluationRequestDto"];
            description: string;
        };
        CreateRiskSubcategoryRequestDto: {
            name: string;
            category: string;
        };
        /** @description The authenticated caller, without minting anything new. */
        CurrentUserDto: {
            roles: string[];
            employee: components["schemas"]["EmployeeResponseDto"];
        };
        DepartmentEngagementStatsDto: {
            /** Format: int64 */
            departmentId: number | string;
            departmentName: string;
            /** Format: int32 */
            activeEmployees: number | string;
            /** Format: int32 */
            employeesWithQuizCompletion: number | string;
            /** Format: double */
            awarenessPercentage: number | string;
        };
        DepartmentMaturityDto: {
            departmentName: string;
            /** Format: double */
            maturityScore: number | string;
        };
        DepartmentResponseDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            branchLocation: string;
        };
        EarlyWarningIndicatorsDto: {
            /** Format: int32 */
            criticalResidualRisks: number | string;
            /** Format: int32 */
            weakControls: number | string;
            /** Format: int32 */
            pendingReview: number | string;
        };
        EmployeeDepartmentStatsDto: {
            /** Format: int64 */
            departmentId: number | string;
            departmentName: string;
            /** Format: int32 */
            activeEmployees: number | string;
            /** Format: int32 */
            employeesWithQuizCompletion: number | string;
            /** Format: double */
            awarenessPercentage: number | string;
            /** Format: int32 */
            riskReportCount: number | string;
        };
        EmployeeResponseDto: {
            /** Format: int64 */
            id: number | string;
            identityUserId: string;
            email: string;
            name: string;
            department: components["schemas"]["DepartmentResponseDto"];
            active: boolean;
            /** Format: date-time */
            createdAt: string;
        };
        /** Format: binary */
        IFormFile: string;
        /** @description Open risks plotted on the 5x5 severity-by-frequency grid, before controls. */
        InherentRiskMatrixDto: {
            cells: components["schemas"]["RiskMatrixCellDto"][];
        };
        LoginDto: {
            email: string;
            password: string;
        };
        PagedResultDtoOfRiskActionResponseDto: {
            items: components["schemas"]["RiskActionResponseDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        PagedResultDtoOfRiskReportResponseDto: {
            items: components["schemas"]["RiskReportResponseDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        PagedResultDtoOfRiskReportStatusHistoryResponseDto: {
            items: components["schemas"]["RiskReportStatusHistoryResponseDto"][];
            /** Format: int32 */
            page: number | string;
            /** Format: int32 */
            pageSize: number | string;
            /** Format: int32 */
            totalCount: number | string;
            /** Format: int32 */
            totalPages: number | string;
        };
        PatchResourceRequestDto: {
            name?: null | string;
            description?: null | string;
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number | string;
            detail?: null | string;
            instance?: null | string;
        };
        RecordResourceEngagementRequestDto: {
            /** Format: int64 */
            empId: number | string;
            /** Format: int64 */
            resourceId: number | string;
            viewed: boolean;
            surveyCompleted: null | boolean;
        };
        /** @description An administrator setting a new password for an employee who cannot sign in. */
        ResetPasswordDto: {
            newPassword: string;
        };
        /** @description Open risks counted per residual band, so the effect of controls is visible. */
        ResidualRiskBandDto: {
            band: string;
            /** Format: int32 */
            count: number | string;
        };
        ResourceEngagementResponseDto: {
            /** Format: int64 */
            id: number | string;
            employee: components["schemas"]["EmployeeResponseDto"];
            resource: components["schemas"]["ResourceResponseDto"];
            viewed: boolean;
            surveyCompleted: null | boolean;
            /** Format: date-time */
            viewedAt: null | string;
            /** Format: date-time */
            completedAt: null | string;
        };
        /**
         * @description Engagement for one resource, counted over the people it is actually aimed at.
         *     Administrators curate the library rather than consume it, so they are excluded from both
         *     the count and the denominator — otherwise every resource would look permanently
         *     under-read by however many admins exist.
         */
        ResourceEngagementStatsDto: {
            /** Format: int64 */
            resourceId: number | string;
            resourceName: string;
            resourceType: string;
            /** Format: int32 */
            viewCount: number | string;
            /** Format: int32 */
            quizCompletionCount: number | string;
            /** Format: double */
            completionRate: number | string;
            /** Format: int32 */
            eligibleEmployees: number | string;
        };
        ResourceResponseDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            uploadedBy: components["schemas"]["EmployeeResponseDto"];
            url: string;
            type: string;
            description: null | string;
            /** Format: date-time */
            uploadedAt: string;
        };
        RiskActionResponseDto: {
            /** Format: int64 */
            id: number | string;
            /** Format: int64 */
            reportId: number | string;
            title: string;
            description: null | string;
            assignee: components["schemas"]["EmployeeResponseDto"];
            /** Format: date-time */
            dueDate: string;
            status: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt: null | string;
        };
        RiskActionSummaryDto: {
            /** Format: int32 */
            overdueCount: number | string;
            /** Format: int32 */
            dueThisWeekCount: number | string;
        };
        RiskCategoryResponseDto: {
            name: string;
            riskSubcategories: components["schemas"]["RiskSubcategoryDto"][];
        };
        RiskMatrixCellDto: {
            /** Format: int32 */
            severity: number | string;
            /** Format: int32 */
            frequency: number | string;
            /** Format: int32 */
            count: number | string;
        };
        RiskReportEvaluationResponseDto: {
            /** Format: int64 */
            id: number | string;
            evaluator: components["schemas"]["EmployeeResponseDto"];
            /** Format: int32 */
            severity: number | string;
            /** Format: int32 */
            frequency: number | string;
            /** Format: int32 */
            controlEffectiveness: number | string;
            /** Format: int32 */
            inherentRisk: number | string;
            /** Format: int32 */
            residualRisk: number | string;
            existingMeasures: null | string;
            proposedMeasures: null | string;
            /** Format: int32 */
            priority: number | string;
            /** Format: date-time */
            evaluatedAt: string;
        };
        RiskReportResponseDto: {
            /** Format: int64 */
            id: number | string;
            reporter: components["schemas"]["EmployeeResponseDto"];
            subCategory: components["schemas"]["RiskSubcategoryResponseDto"];
            reportedEvaluation: components["schemas"]["RiskReportEvaluationResponseDto"];
            auditorEvaluation: null | components["schemas"]["RiskReportEvaluationResponseDto"];
            description: string;
            status: string;
            /** Format: date-time */
            submittedAt: string;
        };
        RiskReportStatusHistoryResponseDto: {
            /** Format: int64 */
            id: number | string;
            /** Format: int64 */
            reportId: number | string;
            changedBy: components["schemas"]["EmployeeResponseDto"];
            oldStatus: string;
            newStatus: string;
            /** Format: date-time */
            changedAt: string;
        };
        RiskSubcategoryDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
        };
        RiskSubcategoryResponseDto: {
            /** Format: int64 */
            id: number | string;
            name: string;
            category: string;
        };
        UpdateEmployeeRequestDto: {
            name: string;
            /** Format: int64 */
            deptId: number | string;
            active: boolean;
        };
        UpdateRiskActionRequestDto: {
            title: string;
            description: null | string;
            /** Format: int64 */
            assigneeEmpId: number | string;
            /** Format: date-time */
            dueDate: string;
            status: string;
        };
        UpdateRiskReportStatusRequestDto: {
            newStatus: string;
        };
        UpdateRiskSubcategoryRequestDto: {
            name: string;
            category: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
